version: '3'

services:
  myapp:
    image: petrovvd/pg_pdo
    volumes: 
      - ./:/var/www/html
    ports:
      - 9000:80
  my_db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: testDB
    volumes:
      - ./test.sql:/docker-entrypoint-initdb.d/test.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080