apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy-replicas
  labels:
    app: myk8s-application
spec:
  replicas: 1
  selector:
    matchLabels:
      project: php
  template:
    metadata:
      labels:
        project: php
    spec:
      containers:
        - name: my-app
          image: petrovvd/app_test
          ports:
            - containerPort: 9000
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2-deploy-replicas
  labels:
    app: myk8s-application2
spec:
  replicas: 1
  selector:
    matchLabels:
      project: php2
  template:
    metadata:
      labels:
        project: php2
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          ports:
            - containerPort: 3306
        - name: phpmyadmin
          image: phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_ARBITRARY
              value: "1"    
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: my-single-pod-service
  labels:
    env  : prod
    owner: DenisAstahov
spec:
  selector:
    project: php2    # Selecting PODS with those Labels
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80  # Port on Load Balancer
      targetPort: 80  # Port on POD
    - name      : app-listener2
      protocol  : TCP
      port      : 3306  # Port on Load Balancer
      targetPort: 3306  # Port on POD
  type: LoadBalancer